apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka-streaming

resources:
  - namespace.yaml
  - kafka.yaml
  - producer.yaml
  - consumers.yaml

commonLabels:
  app.kubernetes.io/name: kafka-streaming
  app.kubernetes.io/instance: example-05
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: streaming
  app.kubernetes.io/part-of: mop-examples
  app.kubernetes.io/managed-by: kustomize
