apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-app-config
  namespace: sql-app
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: orders
  DB_SSLMODE: disable
  DB_MAX_CONNS: "25"
  DB_MIN_CONNS: "5"
  DB_MAX_CONN_LIFETIME: "3600"
  DB_MAX_CONN_IDLE_TIME: "300"
  SERVER_PORT: "8080"
