apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sql-app

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-configmap.yaml
  - postgres-statefulset.yaml
  - app-configmap.yaml
  - app-deployment.yaml

labels:
  - pairs:
      example: sql-app
      managed-by: kustomize
