apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- hpa.yaml

commonLabels:
  app.kubernetes.io/name: http-api
  app.kubernetes.io/component: example
  app.kubernetes.io/part-of: mop

images:
- name: http-api
  newName: http-api
  newTag: latest
