apiVersion: v1
kind: Namespace
metadata:
  name: observability-dev
  labels:
    app: mop
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability-staging
  labels:
    app: mop
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability-production
  labels:
    app: mop
    environment: production